### ISSUE TITLE
svgcheck dependency on macOS

### ISSUE THREAD

**Issue by chris-wood** [cabo/kramdown-rfc#177]
Adding support for SVG graphics is kind of a pain right now. It doesn't "just work." I had to manually install `aasvg` via `npm`. And then when I install `svgcheck` via `pip3` I still get the following:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - svgcheck (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:281:in `capture3'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:548:in `svg_tool_process'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:464:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:464:in `rescue in memoize'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:460:in `memoize'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:615:in `convert_codeblock'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:333:in `block in inner_a'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:331:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:331:in `inner_a'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:338:in `inner'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:1376:in `convert_root'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:326:in `convert1'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:321:in `convert'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-2.4.0/lib/kramdown/converter/base.rb:107:in `convert'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-2.4.0/lib/kramdown/document.rb:116:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc/command.rb:570:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/bin/kramdown-rfc2629:3:in `<top (required)>'
	from /usr/local/bin/kramdown-rfc2629:23:in `load'
	from /usr/local/bin/kramdown-rfc2629:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:461:in `binread': No such file or directory @ rb_sysopen - /Users/caw/.cache/xml2rfc/kdrfc-1_6_12-svg_tool_process-ce7badcc7e9368b4d79a89d784aefbffb23c5517.cache (Errno::ENOENT)
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:461:in `memoize'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:615:in `convert_codeblock'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:333:in `block in inner_a'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:331:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:331:in `inner_a'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:338:in `inner'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:1376:in `convert_root'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:326:in `convert1'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc2629.rb:321:in `convert'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-2.4.0/lib/kramdown/converter/base.rb:107:in `convert'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-2.4.0/lib/kramdown/document.rb:116:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/lib/kramdown-rfc/command.rb:570:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/kramdown-rfc2629-1.6.12/bin/kramdown-rfc2629:3:in `<top (required)>'
	from /usr/local/bin/kramdown-rfc2629:23:in `load'
	from /usr/local/bin/kramdown-rfc2629:23:in `<main>'
Error: Unable to parse the XML document: /dev/stdin
```

**Comment by cabo** [comment]
> I had to manually install `aasvg` via `npm`. 

Indeed.  Or you use one of Martin's docker instances...

> And then when I install `svgcheck` via `pip3` I still get the following:
> 
> ```
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - svgcheck (Errno::ENOENT)

Apparently, svgcheck is not in your path.  Can you check that pip3-installed items get on your path?

The combination between three implementation platforms (Ruby, JS, Python) does not help here.
This is definitely harder to use than it should be.

**Comment by chris-wood** [comment]
> Apparently, svgcheck is not in your path. Can you check that pip3-installed items get on your path?

It is installed, but the pip3 items aren't in my path. I could force that to be the case, but it seems less than ideal. 

> The combination between three implementation platforms (Ruby, JS, Python) does not help here.

Yeah. Can we drop this dependency? What does it actually give us?

**Comment by cabo** [comment]
svgcheck is used to convert SVG into the RFC 7996 dialect.
I haven't checked whether this is actually needed for aasvg; it sure is for most other tools.
@martinthomson -- do you know?

**Comment by martinthomson** [comment]
I can guarantee that aasvg will generate SVG that meets the profile already.  There is one option that will break that guarantee, but that is clearly labelled.

@chris-wood are you using my toolchain?  I have `svgcheck` in the `requirements.txt` there, so it should have been installed for you.  As for `aasvg`, if you create a `package.json` with `npm install --save aasvg; git add package.json; git commit package.json`, then magic should happen.

**Comment by cabo** [comment]
@chris-wood: Please check 1.6.17: This should no longer require svgcheck alongside aasvg, easing this burden as far as I can think taking it.
